### ISSUE TITLE
request: npm version for frontend use (without node core modules 'fs', 'path')

### ISSUE THREAD

**Issue by Monkey-Maestro** [hobuinc/laz-perf#135]
We would love to use this library in our react frontend. Unfortunately with webpack 5 all polyfill node core modules were removed making it a pain to use modules that rely on/use 'fs' and 'path' dependencies.
Is there a plan for a frontend version of this library without node core dependencies? That would be awesome.

**Comment by connormanning** [comment]
I don't fully understand the issue here - what exactly are you running into that is stopping you from using this package?  Yes, the JS bootstrapping code (generated by Emscripten) includes references to NodeJS types like fs/path.  But if you are running in a browser environment, the execution paths will never actually run any of that code.

To me this sounds like an issue with a downstream webpack configuration, or potentially an issue that should be filed against the Emscripten project if there is some specific blocker.  For example, this project as-is is used downstream in [COPC/EPT Cesium viewer](https://viewer.copc.io/?copc=https://s3.amazonaws.com/hobu-lidar/sofi.copc.laz) so I don't think there's anything fundamentally wrong with the output that would prevent it from working in a browser.

It would be useful for me to see:
- Exactly what issue do you run into that makes it a "pain" to use in your build environment:
  - do you need to set the bundling configuration in an overly complicated way?
  - can you not bundle your downstream code at all due to some webpack blocker?
  - are you creating a bundle but it doesn't work properly when executed?
- A PR with the changes that you would consider a solution to these issues
